export type Book = {
  id: string;
  title: string;
  author: string;
  price: number;
  description: string;
  coverImage: string;
  genre: string;
  isbn: string;
  rating: number;
  stock: number;
  pages: number;
  language: string;
  publishedYear: number;
};

export const genres = [
  'Classic',
  'Dystopian',
  'Fantasy',
  'Science Fiction',
  'Adventure',
  'Literary Fiction',
];

export const books: Book[] = [
  {
    id: '1',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    price: 10.99,
    description: 'A novel by Harper Lee published in 1960. Instantly successful, widely read in high schools and middle schools in the United States, it has become a classic of modern American literature, winning the Pulitzer Prize.',
    coverImage: 'https://picsum.photos/seed/book1/400/600',
    genre: 'Classic',
    isbn: '978-0-06-112008-4',
    rating: 4.8,
    stock: 25,
    pages: 324,
    language: 'English',
    publishedYear: 1960,
  },
  {
    id: '2',
    title: '1984',
    author: 'George Orwell',
    price: 9.99,
    description: 'A dystopian social science fiction novel and cautionary tale by English writer George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell\'s ninth and final book completed in his lifetime.',
    coverImage: 'https://picsum.photos/seed/book2/400/600',
    genre: 'Dystopian',
    isbn: '978-0-452-28423-4',
    rating: 4.7,
    stock: 30,
    pages: 328,
    language: 'English',
    publishedYear: 1949,
  },
  {
    id: '3',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 12.50,
    description: 'A 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway\'s interactions with mysterious millionaire Jay Gatsby and Gatsby\'s obsession to reunite with his former love, Daisy Buchanan.',
    coverImage: 'https://picsum.photos/seed/book3/400/600',
    genre: 'Classic',
    isbn: '978-0-7432-7356-5',
    rating: 4.5,
    stock: 15,
    pages: 180,
    language: 'English',
    publishedYear: 1925,
  },
  {
    id: '4',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    price: 8.99,
    description: 'A romantic novel of manners written by Jane Austen in 1813. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.',
    coverImage: 'https://picsum.photos/seed/book4/400/600',
    genre: 'Classic',
    isbn: '978-1-60450-405-3',
    rating: 4.9,
    stock: 40,
    pages: 279,
    language: 'English',
    publishedYear: 1813,
  },
  {
    id: '5',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    price: 11.25,
    description: 'A novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951. It was originally intended for adults but is often read by adolescents for its themes of angst, alienation, and as a critique on superficiality in society.',
    coverImage: 'https://picsum.photos/seed/book5/400/600',
    genre: 'Literary Fiction',
    isbn: '978-0-316-76948-0',
    rating: 4.2,
    stock: 22,
    pages: 224,
    language: 'English',
    publishedYear: 1951,
  },
  {
    id: '6',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    price: 14.99,
    description: 'A children\'s fantasy novel by English author J. R. R. Tolkien. It was published on 21 September 1937 to wide critical acclaim, being nominated for the Carnegie Medal and awarded a prize from the New York Herald Tribune for best juvenile fiction.',
    coverImage: 'https://picsum.photos/seed/book6/400/600',
    genre: 'Fantasy',
    isbn: '978-0-618-00221-4',
    rating: 4.9,
    stock: 50,
    pages: 310,
    language: 'English',
    publishedYear: 1937,
  },
  {
    id: '7',
    title: 'Dune',
    author: 'Frank Herbert',
    price: 18.00,
    description: 'A 1965 science fiction novel by American author Frank Herbert, originally published as two separate serials in Analog magazine. It tied with Roger Zelazny\'s ...And Call Me Conrad for the Hugo Award in 1966, and it won the inaugural Nebula Award for Best Novel.',
    coverImage: 'https://picsum.photos/seed/book7/400/600',
    genre: 'Science Fiction',
    isbn: '978-0-441-01359-3',
    rating: 4.8,
    stock: 18,
    pages: 412,
    language: 'English',
    publishedYear: 1965,
  },
  {
    id: '8',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    price: 10.50,
    description: 'A dystopian novel by English author Aldous Huxley, written in 1931 and published in 1932. Largely set in a futuristic World State, inhabited by genetically modified citizens and an intelligence-based social hierarchy, the novel anticipates huge scientific advancements in reproductive technology, sleep-learning, psychological manipulation and classical conditioning that are combined to make a dystopian society which is challenged by only a single individual: the story\'s protagonist.',
    coverImage: 'https://picsum.photos/seed/book8/400/600',
    genre: 'Dystopian',
    isbn: '978-0-06-085052-4',
    rating: 4.6,
    stock: 28,
    pages: 311,
    language: 'English',
    publishedYear: 1932,
  },
  {
    id: '9',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    price: 25.00,
    description: 'An epic high-fantasy novel by English author and scholar J. R. R. Tolkien. Set in Middle-earth, the story began as a sequel to Tolkien\'s 1937 children\'s book The Hobbit, but eventually developed into a much larger work.',
    coverImage: 'https://picsum.photos/seed/book9/400/600',
    genre: 'Fantasy',
    isbn: '978-0-618-64015-7',
    rating: 5.0,
    stock: 35,
    pages: 1178,
    language: 'English',
    publishedYear: 1954,
  },
  {
    id: '10',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    price: 9.75,
    description: 'A 1953 dystopian novel by American writer Ray Bradbury. It presents an American society where books have been outlawed and "firemen" burn any that are found.',
    coverImage: 'https://picsum.photos/seed/book10/400/600',
    genre: 'Dystopian',
    isbn: '978-1-4516-7331-9',
    rating: 4.5,
    stock: 19,
    pages: 249,
    language: 'English',
    publishedYear: 1953,
  },
  {
    id: '11',
    title: 'Moby Dick',
    author: 'Herman Melville',
    price: 13.99,
    description: 'The saga of Captain Ahab and his relentless pursuit of Moby Dick, the great white whale that crippled him. A masterpiece of American literature, this novel is a profound inquiry into character, faith, and the nature of perception.',
    coverImage: 'https://picsum.photos/seed/book11/400/600',
    genre: 'Adventure',
    isbn: '978-1-5032-8078-6',
    rating: 4.3,
    stock: 12,
    pages: 635,
    language: 'English',
    publishedYear: 1851,
  },
  {
    id: '12',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    price: 12.99,
    description: 'The story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.',
    coverImage: 'https://picsum.photos/seed/book15/400/600',
    genre: 'Fantasy',
    isbn: '978-0-06-231500-7',
    rating: 4.7,
    stock: 60,
    pages: 208,
    language: 'English',
    publishedYear: 1988,
  },
];
